FROM ghcr.io/weaviate/t2v-transformers-models-rs/base-cpu:latest as build
RUN . venv/bin/activate
WORKDIR /app

# Copy our manifests
COPY ./Cargo.toml ./Cargo.toml
COPY ./src ./src
COPY ./ci ./ci

ARG TARGETARCH
ARG MODEL_NAME

ENV MODEL_NAME ${MODEL_NAME}
ENV ONNX_RUNTIME true
ENV ONNX_CPU=${TARGETARCH}

ENV MODEL_DIR "./models/model"
# Download the models
RUN python3 -m ci.download

# Build only the dependencies to cache them
RUN cargo build --release

FROM rust:1.77.1-slim-bookworm as release

COPY --from=build /app/models/model /usr/local/models/model
COPY --from=build /app/target/release/bin /usr/local/bin/t2v-rs

ENV ENABLE_CUDA false
ENV MODEL_PATH /usr/local/models/model/model_quantized.onnx
ENV TOKENIZER_PATH /usr/local/models/model/tokenizer.json

CMD ["/usr/local/bin/t2v-rs"]
