---
version: '3.4'
services:
  t2v-transformers-rs-gpu:
    build:
      context: .
      dockerfile: Dockerfile.gpu
      target: release
      args:
        - MODEL_NAME: "BAAI/bge-small-en-v1.5"
        - TARGETARCH: "arm64"
        - CUDA_VERSION: "12.4.1"
    ports:
      - 3000:3000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  t2v-transformers-rs-cpu:
    build:
      context: .
      dockerfile: Dockerfile.cpu
      target: release
      args:
        - MODEL_NAME: "BAAI/bge-small-en-v1.5"
        - TARGETARCH: "arm64"
    ports:
      - 3000:3000
  t2v-transformers-py-gpu:
    image: semitechnologies/transformers-inference:baai-bge-small-en-v1.5
    ports:
      - 8080:8080
    environment:
      ENABLE_CUDA: "true"
      T2V_TRANSFORMERS_DIRECT_TOKENIZE: "true"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  t2v-transformers-py-cpu:
    image: semitechnologies/transformers-inference:baai-bge-small-en-v1.5-onnx
    ports:
      - 8080:8080
    environment:
      T2V_TRANSFORMERS_DIRECT_TOKENIZE: "true"
...