on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-root-gpu-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cuda: [12.0.1, 12.1.1, 12.2.2, 12.3.2, 12.4.1, 12.5.0]
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: 'Build Root GPU Image'
        run: CUDA_VERSION=${{matrix.cuda}} ./ci/bash/build_root_gpu_image.sh